### ISSUE TITLE
layerを選択しながら複数の操作ができない

### ISSUE THREAD

**Issue by masaru-suzuki** [mentako-ya/mtk64erp#1]
hold時:layer(2)
tap時:Enter
<img width="693" alt="スクリーンショット 2024-11-08 9 54 51" src="https://github.com/user-attachments/assets/be5c96b3-42a6-424f-9b74-0212b5e67f0a">

layer(2)に移動して
*Shiftを押しながらcommand+pのボタンを押すと
command+pのボタンが反応しない問題が発生しています。
<img width="679" alt="SCR-20241108-jdve" src="https://github.com/user-attachments/assets/98b6da08-7689-4041-8ced-e9e518c74a5c">

キースイッチの問題なのか設定の問題なのか判断がつかず、教えていただきたいです🙏

**Comment by masaru-suzuki** [comment]
キースイッチの問題でした。失礼しました。

**Comment by mentako-ya** [comment]
Shiftキー押下時の操作について、キースイッチの問題とのこと、ご報告ありがとうございました
お送りいただいた内容では、レイヤー０のShiftキー位置に「Shift」に設定されているので問題ないかと思いますが、デフォルトのキーマップをそのまま使用した場合、同様の事象が起こり得るケースがありますので、こちらに記載しておきます。

デフォルトのキーマップでは左のShiftキーの位置がShiftではなくMO1（レイヤー1に切り替え）になっています。
https://github.com/mentako-ya/mtk64erp/blob/main/image/remap/remap_layer0.png
レイヤー１にはShiftキー押下時相当のマッピングをセットしてあります。
（レイヤーの仕様方法の一例として設定したものです）
https://github.com/mentako-ya/mtk64erp/blob/main/image/remap/remap_layer1.png
キーキャップの種類（英語配列／日本語配列）とPCのキーボード配列設定が一致しない場合に記号の違いをマッピングで解消できるようにしています。
例えば英字キーキャップでShift+2は＠が印刷されていますが、PCの設定が日本語キーボードの場合、実際は”が入力されます。
このような場合にキーマップでMO1+2に＠をセットすることで、キーキャップと入力される記号の違いを解消できます。

ただし、Shiftキーとしての機能を全て置き換えできないので、このままでは、Shift+command+Pのような操作や、Shift+マウスクリックで複数範囲を選択といった操作ができなくなります。
キーキャップとPC側のキーボード設定が一致している場合は不要な設定ですので、左Shift位置のキーマップはShiftにしていただいた方が良いかと思います。
